Function that can make rdas for all figures/tables
nmfs-ost/satf pull request #28
Opened 2024-11-26 22:40 UTC by sbreitbart-NOAA

2024-12-02 20:00 UTC, Schiano-NOAA commented on R/exp_all_figs_tables.R
Let's discuss this at our meeting

2024-12-02 22:32 UTC, Schiano-NOAA commented on R/exp_all_figs_tables.R
Functions in R only allow you to return one thing at a time. So when I run this, it only gives me the spawning biomass plot (the last one to produce). Wasn't the intention of this to produce a folder with all of the rda files in it? I tried running this with make_rda = TRUE and it didn't do anything other than output the plot in the console

2024-12-02 22:33 UTC, Schiano-NOAA commented on R/exp_all_figs_tables.R
Might need you to walk me through this

2024-12-02 22:34 UTC, Schiano-NOAA requested changes
We need to review this together and I need you to show it to me working because I think I am missing something. I could only plot spawning biomass and it never saved the rda anytime I ran it

2024-12-03 14:11 UTC, Schiano-NOAA commented on R/exp_all_figs_tables.R
My folder was not refreshing yesterday so I didn't see anything created - I now see the folder or RDA files so that is good

2024-12-03 14:36 UTC, Schiano-NOAA commented on R/exp_all_figs_tables.R
> +                         rda_dir)
```suggestion
                         rda_dir) |> suppressWarning()
```

2024-12-03 15:08 UTC, sbreitbart-NOAA commented on R/exp_all_figs_tables.R
> +                         rda_dir)
Will add to upcoming commit

2024-12-03 15:43 UTC, Schiano-NOAA approved these changes
Perfect! Thanks 💯

2024-12-03 15:45 UTC, merged